server:
  port: 8081

spring:
  application:
    name: product-service

resilience4j:
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
  retry:
    instances:
      productService:
        max-attempts: 3
        wait-duration: 1s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.example.ProductService: DEBUG
    io.github.resilience4j: DEBUG