server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3
        wait-duration: 1s
  timelimiter:
    instances:
      productServiceTimeLimiter:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true